<a href="https://colab.research.google.com/github/Harshi-63/Python-Training/blob/main/AirPollution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
data = pd.read_csv('/content/Measurement_info.csv')
data
item = pd.read_csv('/content/Measurement_item_info.csv')
item
station = pd.read_csv('/content/Measurement_station_info.csv')
station

,Station code,Station name(district),Address,Latitude,Longitude
0,101,Jongno-gu,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008
1,102,Jung-gu,"15, Deoksugung-gil, Jung-gu, Seoul, Republic o...",37.564263,126.974676
2,103,Yongsan-gu,"136, Hannam-daero, Yongsan-gu, Seoul, Republic...",37.540033,127.004850
3,104,Eunpyeong-gu,"215, Jinheung-ro, Eunpyeong-gu, Seoul, Republi...",37.609823,126.934848
4,105,Seodaemun-gu,"32, Segeomjeong-ro 4-gil, Seodaemun-gu, Seoul,...",37.593742,126.949679
5,106,Mapo-gu,"10, Poeun-ro 6-gil, Mapo-gu, Seoul, Republic o...",37.555580,126.905597
6,107,Seongdong-gu,"18, Ttukseom-ro 3-gil, Seongdong-gu, Seoul, Re...",37.541864,127.049659
7,108,Gwangjin-gu,"571, Gwangnaru-ro, Gwangjin-gu, Seoul, Republi...",37.547180,127.092493
8,109,Dongdaemun-gu,"43, Cheonho-daero 13-gil, Dongdaemun-gu, Seoul...",37.575743,127.028885
9,110,Jungnang-gu,"369, Yongmasan-ro, Jungnang-gu, Seoul, Republi...",37.584848,127.094023
10,111,Seongbuk-gu,"70, Samyang-ro 2-gil, Seongbuk-gu, Seoul, Repu...",37.606719,127.027279
11,112,Gangbuk-gu,"49, Samyang-ro 139-gil, Gangbuk-gu, Seoul, Rep...",37.647930,127.011952
12,113,Dobong-gu,"34, Sirubong-ro 2-gil, Dobong-gu, Seoul, Repub...",37.654192,127.029088
13,114,Nowon-gu,"17, Sanggye-ro 23-gil, Nowon-gu, Seoul, Republ...",37.658774,127.068505
14,115,Yangcheon-gu,"56, Jungang-ro 52-gil, Yangcheon-gu, Seoul, Re...",37.525939,126.856603
15,116,Gangseo-gu,"71, Gangseo-ro 45da-gil, Gangseo-gu, Seoul, Re...",37.544640,126.835151
16,117,Guro-gu,"45, Gamasan-ro 27-gil, Guro-gu, Seoul, Republi...",37.498498,126.889692
17,118,Geumcheon-gu,"20, Geumha-ro 21-gil, Geumcheon-gu, Seoul, Rep...",37.452357,126.908296
18,119,Yeongdeungpo-gu,"11, Yangsan-ro 23-gil, Yeongdeungpo-gu, Seoul,...",37.525007,126.897370
19,120,Dongjak-gu,"6, Sadang-ro 16a-gil, Dongjak-gu, Seoul, Repub...",37.480917,126.971481
20,121,Gwanak-gu,"14, Sillimdong-gil, Gwanak-gu, Seoul, Republic...",37.487355,126.927102
21,122,Seocho-gu,"16, Sinbanpo-ro 15-gil, Seocho-gu, Seoul, Repu...",37.504547,126.994458
22,123,Gangnam-gu,"426, Hakdong-ro, Gangnam-gu, Seoul, Republic o...",37.517528,127.047470
23,124,Songpa-gu,"236, Baekjegobun-ro, Songpa-gu, Seoul, Republi...",37.502686,127.092509
24,125,Gangdong-gu,"59, Gucheonmyeon-ro 42-gil, Gangdong-gu, Seoul...",37.544962,127.136792

In [42]:
# print(data.columns.tolist())
print(station.columns)

Index(['Station code', 'Station name(district)', 'Address', 'Latitude',
       'Longitude'],
      dtype='object')

# New Section

In [43]:

sub_station = station[['Station code', 'Station name(district)']].drop_duplicates()
sub_station

    Station code Station name(district)
0            101              Jongno-gu
1            102                Jung-gu
2            103             Yongsan-gu
3            104           Eunpyeong-gu
4            105           Seodaemun-gu
5            106                Mapo-gu
6            107           Seongdong-gu
7            108            Gwangjin-gu
8            109          Dongdaemun-gu
9            110            Jungnang-gu
10           111            Seongbuk-gu
11           112             Gangbuk-gu
12           113              Dobong-gu
13           114               Nowon-gu
14           115           Yangcheon-gu
15           116             Gangseo-gu
16           117                Guro-gu
17           118           Geumcheon-gu
18           119        Yeongdeungpo-gu
19           120             Dongjak-gu
20           121              Gwanak-gu
21           122              Seocho-gu
22           123             Gangnam-gu
23           124              Songpa-gu
24           125            Gangdong-gu

In [44]:
data_i = data.merge(item[['Item code', 'Item name']])
data_i

,Measurement date,Station code,Item code,Average value,Instrument status,Item name
0,2017-01-01 00:00,101,1,0.004,0,SO2
1,2017-01-01 00:00,101,3,0.059,0,NO2
2,2017-01-01 00:00,101,5,1.200,0,CO
3,2017-01-01 00:00,101,6,0.002,0,O3
4,2017-01-01 00:00,101,8,73.000,0,PM10
...,...,...,...,...,...,...
3885061,2019-12-31 23:00,123,9,13.000,0,PM2.5
3885062,2019-12-31 23:00,118,9,24.000,0,PM2.5
3885063,2019-12-31 23:00,105,8,19.000,0,PM10
3885064,2019-12-31 23:00,125,3,0.037,0,NO2
3885065,2019-12-31 23:00,108,3,0.030,0,NO2

In [45]:
data_s = data_i.merge(
    station[['Station code', 'Station name(district)']]
)
data_s

,Measurement date,Station code,Item code,Average value,Instrument status,Item name,Station name(district)
0,2017-01-01 00:00,101,1,0.004,0,SO2,Jongno-gu
1,2017-01-01 00:00,101,3,0.059,0,NO2,Jongno-gu
2,2017-01-01 00:00,101,5,1.200,0,CO,Jongno-gu
3,2017-01-01 00:00,101,6,0.002,0,O3,Jongno-gu
4,2017-01-01 00:00,101,8,73.000,0,PM10,Jongno-gu
...,...,...,...,...,...,...,...
3885061,2019-12-31 23:00,123,9,13.000,0,PM2.5,Gangnam-gu
3885062,2019-12-31 23:00,118,9,24.000,0,PM2.5,Geumcheon-gu
3885063,2019-12-31 23:00,105,8,19.000,0,PM10,Seodaemun-gu
3885064,2019-12-31 23:00,125,3,0.037,0,NO2,Gangdong-gu
3885065,2019-12-31 23:00,108,3,0.030,0,NO2,Gwangjin-gu

In [46]:
data = data_s.drop(columns=['Station code', 'Item code'])
data.head()

,Measurement date,Average value,Instrument status,Item name,Station name(district)
0,2017-01-01 00:00,0.004,0,SO2,Jongno-gu
1,2017-01-01 00:00,0.059,0,NO2,Jongno-gu
2,2017-01-01 00:00,1.200,0,CO,Jongno-gu
3,2017-01-01 00:00,0.002,0,O3,Jongno-gu
4,2017-01-01 00:00,73.000,0,PM10,Jongno-gu

In [47]:
# Dictionary already given
status_dict = {
    0: "Normal",
    1: "Need for calibration",
    2: "Abnormal",
    4: "Power cut off",
    8: "Under repair",
    9: "Abnormal data"
}

# Convert dictionary to DataFrame
dictdf = pd.DataFrame(list(status_dict.items()),
                         columns=['Instrument status', 'Instrument Status Name'])

# Merge with data
data = data.merge(dictdf, on='Instrument status', how='left')

# Drop the old column
data = data.drop(columns=['Instrument status'])

data.head()

,Measurement date,Average value,Item name,Station name(district),Instrument Status Name
0,2017-01-01 00:00,0.004,SO2,Jongno-gu,Normal
1,2017-01-01 00:00,0.059,NO2,Jongno-gu,Normal
2,2017-01-01 00:00,1.200,CO,Jongno-gu,Normal
3,2017-01-01 00:00,0.002,O3,Jongno-gu,Normal
4,2017-01-01 00:00,73.000,PM10,Jongno-gu,Normal

In [48]:
# Convert Measurement date to datetime
data['Measurement date'] = pd.to_datetime(data['Measurement date'])

# Extract year, month, day, hour
data['Year'] = data['Measurement date'].dt.year
data['Month'] = data['Measurement date'].dt.month
data['Day'] = data['Measurement date'].dt.day
data['Hour'] = data['Measurement date'].dt.hour

# Drop the original column
data = data.drop(columns=['Measurement date'])

data.head()

,Average value,Item name,Station name(district),Instrument Status Name,Year,Month,Day,Hour
0,0.004,SO2,Jongno-gu,Normal,2017,1,1,0
1,0.059,NO2,Jongno-gu,Normal,2017,1,1,0
2,1.200,CO,Jongno-gu,Normal,2017,1,1,0
3,0.002,O3,Jongno-gu,Normal,2017,1,1,0
4,73.000,PM10,Jongno-gu,Normal,2017,1,1,0