In [48]:
import pandas as pd
from sklearn.datasets import load_breast_cancer,fetch_california_housing
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,precision_score,recall_score,accuracy_score,r2_score,mean_absolute_error

In [49]:
cdata =load_breast_cancer()
df = pd.DataFrame(cdata.data,columns=cdata.feature_names)
df['cancer'] = cdata.target
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,cancer
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [50]:
X = df.drop("cancer", axis=1)
y = df['cancer']

In [51]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [52]:
cmod = RandomForestClassifier(n_estimators=200,max_depth=10)
cmod.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, n_estimators=200)

In [53]:
ypred = cmod.predict(X_test)
ypred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [54]:
print("Training Accuracy:", cmod.score(X_train, y_train))
print("Testing Accuracy:", cmod.score(X_test, y_test))

Training Accuracy: 1.0
Testing Accuracy: 0.9707602339181286

In [55]:
rdata = fetch_california_housing()
rdf = pd.DataFrame(rdata.data,columns=rdata.feature_names)
rdf['target'] = rdata.target
rdf.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [56]:
X = rdf.drop('target', axis=1)
y = rdf['target']

In [57]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3,random_state=42)

In [64]:
rmod = RandomForestRegressor(n_estimators=150,max_depth=10)
rmod.fit(Xtrain,ytrain)

RandomForestRegressor(max_depth=10, n_estimators=150)

In [65]:
ypred =rmod.predict(Xtest)
ypred

array([0.54990483, 0.84493517, 4.73705883, ..., 2.12847911, 1.45715782,
       2.0707136 ])

In [66]:
print('Training Accuracy: ',rmod.score(Xtrain,ytrain))
print('Testing Accuracy:', rmod.score(Xtest,ytest))

Training Accuracy:  0.8755575198116313
Testing Accuracy: 0.7786818503953113

In [67]:
r2_score(ytest, ypred)

0.7786818503953113

In [62]:
mean_absolute_error(ytest, ypred)

0.3668133083106325